package com.wangbo.familychat.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class TRelationShip implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relation_ship.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relation_ship.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relation_ship.friend_id
     *
     * @mbggenerated
     */
    private Long friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relation_ship.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relation_ship.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relation_ship.relation_state
     *
     * @mbggenerated
     */
    private Integer relationState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relation_ship.id
     *
     * @return the value of t_relation_ship.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relation_ship.id
     *
     * @param id the value for t_relation_ship.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relation_ship.user_id
     *
     * @return the value of t_relation_ship.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relation_ship.user_id
     *
     * @param userId the value for t_relation_ship.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relation_ship.friend_id
     *
     * @return the value of t_relation_ship.friend_id
     *
     * @mbggenerated
     */
    public Long getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relation_ship.friend_id
     *
     * @param friendId the value for t_relation_ship.friend_id
     *
     * @mbggenerated
     */
    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relation_ship.create_time
     *
     * @return the value of t_relation_ship.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relation_ship.create_time
     *
     * @param createTime the value for t_relation_ship.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relation_ship.update_time
     *
     * @return the value of t_relation_ship.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relation_ship.update_time
     *
     * @param updateTime the value for t_relation_ship.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_relation_ship.relation_state
     *
     * @return the value of t_relation_ship.relation_state
     *
     * @mbggenerated
     */
    public Integer getRelationState() {
        return relationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_relation_ship.relation_state
     *
     * @param relationState the value for t_relation_ship.relation_state
     *
     * @mbggenerated
     */
    public void setRelationState(Integer relationState) {
        this.relationState = relationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", friendId=").append(friendId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", relationState=").append(relationState);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}