package com.wangbo.familychat.dao;

import com.wangbo.familychat.dao.entity.TRelationShip;
import com.wangbo.familychat.dao.entity.TRelationShipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface TRelationShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    int countByExample(TRelationShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    int deleteByExample(TRelationShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    int insert(TRelationShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    int insertSelective(TRelationShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    List<TRelationShip> selectByExample(TRelationShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    TRelationShip selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TRelationShip record, @Param("example") TRelationShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TRelationShip record, @Param("example") TRelationShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TRelationShip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_relation_ship
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TRelationShip record);
}